### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by MrHighwayTM** [bigbang1112-cz/gbx#23]
When trying to login (Authorize Discord) it does not register the authorization, and loops back to webpage, still not logged in. Endless loop of login attempts. Multiple browsers tried (Firefox and Edge)

**Comment by BigBang1112** [comment]
Thanks for the report, looking into it

**Comment by BigBang1112** [comment]
Fixed with https://github.com/bigbang1112-cz/gbx/commit/f294178864eb7228116275870c4d7550f1b14ba9
Thanks again
